table Orders
	lineageTag: 59575466-7d16-4d29-bc68-f9aace7c8183

	measure 'Total Sales' = sum(Orders[Sales])
		lineageTag: 705ed2ea-06e2-47f5-a11a-899ecdfc8433

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = ```
			sum(Orders[Profit])
			
			```
		lineageTag: 18fb65fb-8b13-4d85-8e9b-1c9f46acf58a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 8c743b67-ec48-4b86-9195-41778c3bad9b
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: b9a31211-3a3f-435d-a768-e24e256f0dab
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: afb04311-9728-4143-b8fb-eb4adb0d9243
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 4be1fbbe-e989-4261-a81c-08e98536b707
			defaultHierarchy: LocalDateTable_be3b104c-ad53-42e5-a5f3-ac6a2c3626a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b27721a9-8b32-485e-8445-7142f961ff45
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 5bbdfb28-77b7-4025-94e7-6cab7242c044
			defaultHierarchy: LocalDateTable_78996501-cb99-405c-8b91-809ab739837f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: f6889971-35c0-485d-8b24-fbe7d13cb069
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 96e22bf7-5940-4564-8f5c-12f821575345
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 149bd29d-e6ff-49f2-9d76-48dd29c45ae1
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: e0f6c05c-12f0-428b-a6b0-e3e9baf13b51
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: b64a4644-f204-4c65-a082-e0ae45aa1776
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6fef07a1-fb83-4edb-9fbf-5375cc196d3e
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 432ba4fb-1d21-411e-9c5e-9e2923f9e634
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: ed9af85a-410c-4ecf-b0e6-791d446a2b68
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c6fbb78f-48c7-4ee3-bcb6-20f37d7a08be
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: a91e955b-a903-42aa-ad79-135b5b5a9555
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d26dce10-1047-447a-8c99-ddd1c75001d3
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: bb4b5fa4-190d-4321-b02a-3d6c0efe4309
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 15fe3875-93f9-4bb8-be8c-f3c8009c1e54
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 4b2663c8-4f46-4af6-b452-35192746269c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 74be89f2-ecb5-4074-94e5-048e952af44a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 35eb7978-198a-42d6-91fd-ce58579b9b2f
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 990ea760-0cda-4d49-bce0-dac7f65b13ab
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\samplesuperstore\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

